repository: ktorio/ktorio.github.io
encoding: utf-8
output: web

# this appears in the html browser tab for the site title (seen mostly by search engines, not users)
title: Ktor
description: "Ktor"
url: http://ktor.io

ktor_version: 0.9.1
ktor_version_eap: 0.9.2-alpha-5
kotlin_version: 1.2.31

# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.
github_editme_path: ktorio/ktorio.github.io/edit/master/

# if you have google-analytics ID, put it in. if not, edit this value to blank.
google_analytics: UA-47631155-3

# the preview server used. Leave as is.
host: 127.0.0.1

# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.
port: 4000

# these are the files and directories that jekyll will exclude from the build
exclude:
  - .idea
  - .gitignore
  - Dockerfile
  - docker-build.sh
  - docker-run.sh

# library used for syntax highlighting
highlighter: rouge

# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 entity_output: as_char
 toc_levels: 1..6
 smart_quotes: lsquo,rsquo,ldquo,rdquo
 syntax_highlighter: rouge

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

# these are defaults used for the frontmatter for these file types
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
